## The Basics 



In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype='int32')
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,2.0]])
print(b)


[1 2 3]
[[9. 8. 7.]
 [6. 5. 2.]]


In [3]:
#get dimesion
a.ndim
b.ndim


2

In [4]:
#get shape(how many row and columns consists a matrix)
print(a.shape)
print(b.shape)  #(R X C)

(3,)
(2, 3)


In [5]:
#get type and size
a.dtype
a.itemsize

4

In [6]:
#get size(This means that total elements inside the array)
b.size

6

## Accessing/Changing Specific Elements,rows,columns

In [7]:
#2D array and its all about
#Initialization
c = np.array([[2,3,4,5],[6,7,8,9],[10,11,12,13]])
print(c)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [8]:
#specific data 
c[0,-1] #  v


5

In [9]:
#specified row and column
print(c[0,:])
print(c[:,1])

[2 3 4 5]
[ 3  7 11]


In [10]:
#iterating with steps
#syntax: array_name[start:end:step]
print(c[:,::3])

[[ 2  5]
 [ 6  9]
 [10 13]]


In [11]:
#Changing Array values
print("Before Changing: \n")
print(c)
c[:,2] = [101,102,103] #can be change full row or column in a single statements[if i put 1 then all data change into 1]
c[1,0] = 0 #only one value will be change
print(f"After Changing Values: \n{c}")


Before Changing: 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
After Changing Values: 
[[  2   3 101   5]
 [  0   7 102   9]
 [ 10  11 103  13]]


#### 3D array

In [12]:
#initialization
f = np.array([[[1,2,4],[4,5,6]],[[8,9,20],[22,23,24]]])
print(f)


[[[ 1  2  4]
  [ 4  5  6]]

 [[ 8  9 20]
  [22 23 24]]]


In [13]:
#get specified data 
print(f[0,1,-1]) 
print(f[0,1,:]) 
print(f[0,1,]) 

6
[4 5 6]
[4 5 6]


In [14]:
#array elements change/Replace
f[0,0,2] = 100
f[1,:,:] = [[101,102,103],[104,105,106]]
print(f)


[[[  1   2 100]
  [  4   5   6]]

 [[101 102 103]
  [104 105 106]]]


In [15]:
#all zero's matrix
arr= np.zeros((3,3))
print(arr)
np.zeros(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#all 1's matrix
np.ones((arr.shape),dtype = "int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
#Fill with Any other number
np.full((2,3,3),46)

array([[[46, 46, 46],
        [46, 46, 46],
        [46, 46, 46]],

       [[46, 46, 46],
        [46, 46, 46],
        [46, 46, 46]]])

In [18]:
#any other number (full like)
np.full_like(arr,3,dtype = "int32") #Initially it is in double data types
#it creates a array which is already exists. we just create a different array with the size of the previous 
#array. and fill with a value



array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [46]:
x = np.random.rand(3)
print(x)

[[0.94960938 0.70848094 0.92522947]
 [0.60543537 0.03584464 0.93269721]
 [0.78217524 0.48052509 0.98190136]]


In [42]:
#random number generating in array
np.random.rand(2,4)

array([[0.88710043, 0.95683273, 0.26199655, 0.96191357],
       [0.34061037, 0.73449985, 0.42749946, 0.51323242]])

In [20]:
#random integer value with range 
z=np.random.randint(7,size=(3,3))
print(z)
print("\n")
z = np.random.randint(4,7,size = (4,4))
print(z)

[[1 0 0]
 [0 0 0]
 [4 3 6]]


[[5 5 6 6]
 [6 4 6 5]
 [4 4 4 5]
 [6 4 6 4]]


In [21]:
#identity Matrix
z=np.identity(4)
print(z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
np.repeat(z,3,axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 9., 0.],
       [0., 9., 0.],
       [0., 9., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
A = np.ones((5,5),dtype = "int32")
z = np.zeros((3,3))
z[1,1] = 9
A[1:4,1:4] = z
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Numpy Searching


In [24]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


y=[]
for element in arr:
    if (element==4):
        y.append(True)
        
    else :
        y.append(False)
print(y)
print(*arr[y])


### copying arrays


In [25]:
a = np.array([1,2,3,4])
b = a # it will work like view() function. if we change any elements from original. it will affect original
b[0] = 200
print(a)
print(b)

[200   2   3   4]
[200   2   3   4]


In [26]:
##using copy method 

b = a.copy()
b[0] = 300
print(b)
print(a)

[300   2   3   4]
[200   2   3   4]


## Mathematics 

In [27]:
arr = np.array([2,3,4,6],dtype="int32")
print(arr+2)
print(arr-2)
print(arr//2)
print(arr**3)
print(arr//3)
#we can use sin,cos and other trignometric functions here

[4 5 6 8]
[0 1 2 4]
[1 1 2 3]
[  8  27  64 216]
[0 1 1 2]


In [28]:
b = np.array([10,11,12,14])
a+b


array([210,  13,  15,  18])

## Linear Algebra

In [29]:
a = np.ones((2,3))
b = np.full((2,3),7)


print(a)
print(b)
c =a+b
c= a*b
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[7. 7. 7.]
 [7. 7. 7.]]


## Multiplication 

In [30]:
#Rule: A and B two matrices. Number of columns of A matrix is equal to the 
# number of rows of second Matrix. 

In [31]:
a = np.full((2,3),4)
b = np.ones((3,2))
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])